### PR TITLE
feat: Rate application feature so that users can rate app and provide feedback.

### LINKED ISSUE #621: Rate Application
**Describe the feature you'd like**
Rate application, so that users can rate the application.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by tanmayrauth**
Fixes #621

Screenshot:
ezgif com-video-to-gif (3)

Changes: 
Added rate us menu on navigation drawer. 
On click it will open our application playstore page. Where user can rate application and provide feedback.

### CODE REVIEW

**Comment by adityastic** [comment]
@tanmayrauth resolve conflicts 👍

**Comment by tanmayrauth** [comment]
@adityastic Conflicts are resolved now. Please take a look.

**Comment by adityastic** [comment]
@tanmayrauth please write descriptions as Fixes #Number without [ ].

**Comment by tanmayrauth** [comment]
@aditastic is it correct now?

**Comment by adityastic** [comment]
@tanmayrauth yes, perfect

**Pull request merged**
