### PR TITLE
Changing Level or Mode when Preview Badge is displaying takes effect …

### PR DESCRIPTION
**Pull request by psalmfill**
…without having to click Preview Button to apply change

Fixes #[Add issue number here. If you solve the issue entirely, else please change the message e.g. "First steps or Part of for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by psalmfill** [comment]
@adityastic you can merge now

**Comment by adityastic** [comment]
@psalmfill I am not the admin, @iamareebjamal has the rights to review and merge.

**Comment by psalmfill** [comment]
@adityastic ok.

**Comment by iamareebjamal** [comment]
Follow PR template

**Pull request closed without merging**
