### PR TITLE
enhancement : Improve and Simplify UI and Colors

### LINKED ISSUE #248: Improve and Simplify UI and Colors
Please improve the UI as follows:

* Make sections Speed, Animations, Effects in a kind of sub tabs as in the mockup below
* Use one standard red in all areas (the same red as on the top menu bar) - also for the highlighted areas - use the same red!
* Delete "Text to Send"

57098056-d3c3d900-6d36-11e9-8472-1ef7fe67b25c

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #248 

Changes: 
- Added a Tablayout which switches between Effects, Animation and Speed

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @mariobehling @iamareebjamal Please Review

**Comment by mariobehling** [comment]
Thank you. Could you help after that to show all Cliparts on the screen once the user clicks "Clipart" (instead of having the movable bar). https://github.com/fossasia/badge-magic-android/issues/240

**Comment by adityastic** [comment]
@mariobehling definitely sir, will do that as well

**Comment by mariobehling** [comment]
Also see here, please: https://github.com/fossasia/badge-magic-android/issues/250

**Comment by adityastic** [comment]
> Also see here, please: #250

Got it sir

**Pull request merged**
