### PR TITLE
Implement a badge preview on the top of the screen

### PR DESCRIPTION
**Pull request by adityastic**
Motive : Implement a badge preview on the top of the screen

Changes: [
- Created a Custom Layout (PreviewBadge.kt) for getting the complete visual feel of the LED
- Added seperate data classes(Cell.kt, CheckList.kt) for better management
- Changes to MessageActivity to incorporate Support for Badge
- Vector Drawable's for LED
- Added Function in Presenter(MessagePresenter.kt) to take care of the hex conversions
- Changes to Message Activity XML
]

Screenshots for the change:

Screenshot_20190325-144859_Badge Magic
Screenshot_20190325-144909_Badge Magic

### CODE REVIEW

**Comment by mohitm15** [comment]
Some checks were although!!

**Comment by mohitm15** [comment]
Failed

**Comment by yashk2000** [comment]
@adityastic this isn't the way to work on an issue. Someone else was already working on this issue and has already sent a pull request. Your should first ask the other person before starting to work on the same issue.

**Comment by adityastic** [comment]
@yashk2000 I am so sorry, I thought about implementing the bitmaps to this project. But the first step was to get the base ready. What do you want me to do about it now? should I delete it?

**Comment by adityastic** [comment]
@mohitm15 Yes Sir, I'm afraid I missed the strings file

**Comment by yashk2000** [comment]
@adityastic you've done good work. But you should ask the creator of the previous pull request. Since he was already working on this issue. If he says that it's alright for you to work on it, then continue working on it.

**Comment by adityastic** [comment]
@yashk2000  Alright Sir. Thanks :)

**Comment by yashk2000** [comment]
There's no need to call anyone sir @adityastic. We're all learners here and ready to help:)

**Comment by mohitm15** [comment]
No need to call us sir 😅 @adityastic . However discuss about the changes you had made to whom who had already claimed for that issue , then proceed further.

**Pull request closed without merging**
