### PR TITLE
fix: Created a seperate file for landscape orientation.

### LINKED ISSUE #106: Visibility of badge in landscape mode.
**Describe the bug**
In landscape mode, the badge preview is not fully visible.

**To Reproduce**
Shift to landscape mode.

**Expected behavior**
Badge preview should be completely visible.

**Screenshots**

screencap

**Additional Context**
The size of the text "Badge Magic" also decreases on the top. That should also not happen.

**Would you like to work on the issue?**
YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #106 

Changes: A new layout resource file has been added for landscape orientation.

Screenshots for the change:

screencap

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @adityastic @yatri1609 please review.

**Comment by iamareebjamal** [comment]
No need to recreate entire layout just for a widget. Either, fix the widget or use dimens

**Comment by yashk2000** [comment]
@iamareebjamal the height of the preview badge is fixed to 135dp in the xml. In landscape mode, the same height remains, while the height has to be increased so that the complete badge is visible. It is not a problem with the widget. 

> No need to recreate entire layout just for a widget. Either, fix the widget or use dimens

Could you please tell me what do you mean by use dimens?

**Comment by iamareebjamal** [comment]
create a dimen and override in values-land

**Comment by iamareebjamal** [comment]
@yashk2000 It should not be fixed then right? It should maintain its aspect ratio like all other widgets

**Pull request closed without merging**
