### PR TITLE
UI Improvement and Build Updated

### PR DESCRIPTION
**Pull request by rishabhj126**
Updated the Build version according to new play services rules and Updated UI with an Icon Added

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hi, Can you provide some screenshots for the changes and squash all the commits into one?

**Comment by rishabhj126** [comment]
screenshot_2019-02-26-18-27-46-982_com nilhcem blenamebadge
screenshot_2019-02-26-18-28-18-922_com nilhcem blenamebadge
screenshot_2019-02-26-18-27-41-066_com nilhcem blenamebadge
Here are some screenshot to the application

**Comment by mariobehling** [comment]
Hi, I don't understand what specific improvements you have made. Did you have a look at this app: https://play.google.com/store/apps/details?id=com.rooftopSpace.Led Please check it out and see if you can get any inspiration from that. Rather than making many changes, please open issues and make one change at a time that is a clear improvement, e.g. implement previews.

**Comment by mariobehling** [comment]
Please check if you could help with this issue: https://github.com/fossasia/badge-magic-android/issues/14

And please follow best practices. First open an issue with info on specific improvements and then match a PR with this issue: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

I am closing this and look forward to PRs that are easier to review following our best practices. Thanks.

**Pull request closed without merging**
