### PR TITLE
enhancement: Center speed button, add number in the button

### LINKED ISSUE #353: Center speed button, add number in the button
Please center the speed button and move the number for the speed into the middle of the button itself.
Screenshot 2019-06-07 at 3 15 54 PM

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #353 

Changes: 
- improved layout to fit text in center

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @iamareebjamal @mariobehling Please Review

**Comment by mariobehling** [comment]
Looks good, but could you increase the size of the circle a little bit. However leave the size of the number as is.

**Comment by adityastic** [comment]
@mariobehling yes sir, sure

**Comment by adityastic** [comment]
@mariobehling Updated, made it a bit bigger

**Comment by mariobehling** [comment]
Very good.

**Pull request merged**
