### PR TITLE
Added Launcher Icon

### LINKED ISSUE #77: Make an icon for the app.
**Describe the chore**
There should be an icon for the app instead of the default android logo.

**Would you like to work on the issue?**
YES.

I was thinking of making the icon like the badgeyay website. Could you please give your opinions @iamareebjamal @mariobehling of how the app icon should be designed?

### PR DESCRIPTION
**Pull request by rishabhj126**
Fixes #77
Launcher Icon added

### CODE REVIEW

**Comment by rishabhj126** [comment]
Badgemagic
Launcher Icon Preview

**Comment by adityastic** [comment]
@rishabhj126 did you create any more options?

**Comment by rishabhj126** [comment]
I have cropped the same image to all android shapes for maintaining uniformity

> @rishabhj126 did you create any more options?

I have cropped the same image to all android shapes for maintaining uniformity

**Comment by adityastic** [comment]
@rishabhj126 Sorry if I confused you. I meant, did you create any other icons as options?

**Comment by adityastic** [comment]
icon

A Suggestion.
@yashk2000 @yatri1609 @iamareebjamal @anhanh11001. What do you guys think? I can be more creative if you want

**Comment by yashk2000** [comment]
It looks good. But maybe you could replace the green color with the same red color as the app's primary theme?

**Comment by adityastic** [comment]
icon
iconpsd-2
iconpsd-3

@yashk2000 @iamareebjamal

**Comment by adityastic** [comment]
iconpsd-4
@yashk2000 @iamareebjamal, another design

**Comment by adityastic** [comment]
Just samples, you guys can decide the rest

**Comment by iamareebjamal** [comment]
Where are the icons from, are they free for use and modifications, what is their license, are they vector?

**Comment by adityastic** [comment]
@iamareebjamal Yes, they are free to use. They are not vectors, I can recreate them to vectors if you approve the design

**Comment by adityastic** [comment]
@iamareebjamal it's on Creative Commons license

**Comment by adityastic** [comment]
@iamareebjamal I'm only talking about the led icon, the background is created by me

**Comment by iamareebjamal** [comment]
Please share the source and convert to vectors

**Comment by adityastic** [comment]
@iamareebjamal yatri is working on another icon. They told me to wait

**Comment by adityastic** [comment]
@iamareebjamal check the gitter channel, I have created another icon from scratch which matches our badge

**Comment by iamareebjamal** [comment]
Add it here and take a vote among peers

**Comment by adityastic** [comment]
Alright Sir @iamareebjamal . In 15 mins I'll be back home and post it here

**Comment by adityastic** [comment]
iconpsd-5
@iamareebjamal

**Comment by adityastic** [comment]
iconpsd-7
iconpsd-6

Colors can be changed anytime, You just need to check the design you like

**Comment by adityastic** [comment]
@yashk2000 @yatri1609

**Comment by adityastic** [comment]
@anhanh11001 @rishabhj126

**Comment by adityastic** [comment]
@yashk2000 @iamareebjamal please vote

**Comment by adityastic** [comment]
@iamareebjamal this can now be closed

**Pull request closed without merging**
