### PR TITLE
chore: Updated screenshots

### LINKED ISSUE #347: Update screenshots in the readme.
**Describe the chore**

Screenshots of the app should be updated in the readme along with text+clipart mode in the badge.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #347 

Changes: Added screenshots of the latest UI to the readme.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @mariobehling @iamareebjamal please review.

**Comment by mariobehling** [comment]
Could you please check that every png is substituted. Looks like there is a different naming for some updated ones.

**Comment by adityastic** [comment]
@mariobehling hard represents hardware image.

**Comment by yashk2000** [comment]
> Could you please check that every png is substituted. Looks like there is a different naming for some updated ones.

@mariobehling the naming convention is the same, just the images have been changed. 
`screen-1.png` represents the settings on the app in a device and `screen-1-hard.png` is the corresponding appearance on the hardware.

**Comment by mariobehling** [comment]
You are deleting  docs/images/screen-4-hard.png and  docs/images/screen-6-hard.png, but I don't see a new one.

**Comment by yashk2000** [comment]
@mariobehling they have not been deleted. They have been shown with a 38% and 55% change in their sizes. All the screenshots and hardware images are properly visible in the readme. 
You can check it out [here](https://github.com/yashk2000/badge-magic-android/tree/ss_update).

**Comment by adityastic** [comment]
@yashk2000, the permission changed for those files, please check
Screenshot 2019-06-10 at 1 26 34 PM

**Comment by yashk2000** [comment]
@adityastic I did not get the problem. What permission has been changed?

**Comment by adityastic** [comment]
@yashk2000 check the files permission in the screenshot, 644 to 755.

**Comment by yashk2000** [comment]
@adityastic sorry for the delay. I do not know how to permission got changed. I just replaced the existing pictures with new ones. I'll open a new pt with these screenshots.

**Pull request closed without merging**
