### PR TITLE
Improve/ux send bytes

### LINKED ISSUE #49: Improve UX for sending bytes
### Description
currently User clicks send , No visual representation is shown
button becomes non-responsive

### ScreenShots
Non Responsive UX when sendBytes() works

### Expected UX
1) Details(Or Name) of device where bytes are being sent should be shown to user
2) Progress when bytes are being sent to user
3) failure message when sendBytes() fails
4) `Send` button should be disabled when bluetooth found

### Would you like to work
 YES

### PR DESCRIPTION
**Pull request by theLimitBreaker**
Fixes Complete #49 and  Complete #50 

### Update 

Also Fix complete #42 

Changes: 

For #49 
Add Loader while data is being sent
Proper information about data is sent or not or not able to find device
Show Id of Device to which data is being sent

For #50 
Handle NPE when characterStic is null

Screenshots for the change:

### CODE REVIEW

**Comment by yashk2000** [comment]
@theLimitBreaker did you check the "Data Sent" condition on a real BLE device?

**Comment by theLimitBreaker** [comment]
@yashk2000  yes !!

**Comment by yashk2000** [comment]
Could you please tell me from where did you buy the device?

**Comment by yashk2000** [comment]
And what happens in case a Bluetooth device other that BLE is connected to your phone and you are trying to send the badge details?

**Comment by theLimitBreaker** [comment]
I tried with MI band 3 it just said It "Data Sent" . And I didn't send any badge details.

**Comment by yashk2000** [comment]
That shouldn't be the case, it should show data sent only when data is sent to an actual BLE device and not to any random Bluetooth device. I am already working on this as I have created #42. So pllease leave out the message portion from your pr as I am already working on it.

**Comment by theLimitBreaker** [comment]
Mi Band 3 is BLE device . It didn't scan any Bluetooth device (For example : Phone )
Further . I haven't change any thing regarding Bluetooth scanning and connecting and sending bytes .

If you would look into changes . I have just added callback to notify successful and unsuccessful data sending information .

**Comment by yashk2000** [comment]
I meant that "Data Sent" snackbar should be shown only if data is sent to the Bluetooth LED badge. The Mi Band 3 is not a Bluetooth LED badge. 

And notifying whether data was sent successfully or not is a part of #42 which I am working on. Just remove the part where you are giving the notification of success or failure. Rest is fine.

**Comment by theLimitBreaker** [comment]
Ok ! I will remove it .
But snackbar is shown only when callback `onConnected` is true . 
If it's `onConnected` is true for MI Band 3 than there is some problem with Gattclient .

**Comment by yashk2000** [comment]
Thanks :)

When you are connected to the Mi band and press send, can you please tell what the logcat shows? It would show "Scan could not find any device" or "Device found:" with the device ID. If it shows device found, please check and tell whether it shows "Data sent" or not in the logcat after that.

**Comment by rishabhj126** [comment]
Please quash all the commits then it will be easier for the reviewer

**Comment by theLimitBreaker** [comment]
@yashk2000 It was device found and then Data sent after that only I placed the callback for successful notification

**Comment by yashk2000** [comment]
Ok. It's fine then. And please undo the snackbars. I'll do it as I'm doing #42.

**Comment by theLimitBreaker** [comment]
You mean , removing `callbacks for successful/unsuccessful data send`?
If so then that would mean removing the loader, and Display Device Information .

**Comment by yashk2000** [comment]
If it means undoing that many changes, leave it as it is. Just tag my issue too above where you've mentioned the other issues that were solved so that #42 will also be closed when this pr is merged.

**Comment by theLimitBreaker** [comment]
Updated ! Thank you @yashk2000

**Comment by theLimitBreaker** [comment]
> Please squash all the commits then it will be easier for the reviewer

I have squashed the commits now

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by theLimitBreaker** [comment]
Sure ! will do

**Comment by cweitat** [comment]
Conflicts.

**Comment by theLimitBreaker** [comment]
Closing this , as files have been changed drastically . issue #49 is not relevant now

**Pull request closed without merging**
