### PR TITLE
fix: added a transfer button on the right of send button 

### LINKED ISSUE #235: Instead of "play" button we need a button "transfer/upload to device"
The red play button is not suitable for the transfer functionality. As a first step to simplify the UI, please implement a button "Transfer" next to the "Save" button in the UI.

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #235 

Changes:
- Removed Floating Button completely
- Added a Transfer Button on the Right of the send button
- Made BottomBar Invisible for now

Screenshots for the change:
issue_235

### CODE REVIEW

**Comment by adityastic** [comment]
@mariobehling Please Review

**Comment by adityastic** [comment]
@yashk2000 Please Review

**Comment by yashk2000** [comment]
How does it look in the saved configurations section?

**Comment by adityastic** [comment]
@yashk2000 Saved Configuration is hidden for now

**Comment by adityastic** [comment]
@yashk2000 it will be handled in the upcoming pr when the whole app will be redesigned

**Comment by yashk2000** [comment]
@adityastic ok. I'd also like to help with the upcoming pr if needed :)

**Pull request merged**
