### PR TITLE
fix: Update latest UI screenshots in Readme

### LINKED ISSUE #580: Update latest UI screenshots in Readme
**Describe the chore**
The current screenshots of UI in the readme file are outdated.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by refactor-droidyy**
Fixes #580 

Screenshots for the change:

https://github.com/refactor-droidyy/badge-magic-android/tree/update

### CODE REVIEW

**Comment by adityastic** [comment]
@refactor-droidyy can you tell me what are the things changed, I'm not able to differentiate any difference

**Comment by refactor-droidyy** [comment]
@adityastic I have changed the new UI screenshots (https://github.com/refactor-droidyy/badge-magic-android/tree/update) as I have named those file as they were previously so that's why they are not showing any change :(

**Comment by refactor-droidyy** [comment]
@adityastic should I add the screenshots.

**Comment by adityastic** [comment]
@refactor-droidyy no it's completely fine. Thanks a ton for the new screenshots 😁😀

**Pull request merged**
