### PR TITLE
fix: Decrease white space above top buttons, increase space above sav…

### LINKED ISSUE #270: Decrease white space above top buttons, increase space above save/transfer, decrease space below save/transfer
The screen does not work entirely well on smaller phones yet. 

The app should be working on **smaller screens as well as on bigger screens without scrolling**.

Therefore please increase/decrease the spacing as follows. Ensure the UI feels/looks naturals. Avoid too small or too large white areas.

Change the following:
* decrease height of buttons
* decrease white space above top buttons
* increase space above save/transfer
* decrease space below save/transfer

Screenshot_2019-05-07-00-07-23-997_com nilhcem blenamebadge

### PR DESCRIPTION
**Pull request by adityastic**
…e/transfer, decrease space below save/transfer

Fixes #270 

Changes:
- Updated the layout with minor changes should fix the layout issues in small devices

Screenshot 2019-06-07 at 3 15 54 PM

### CODE REVIEW

**Comment by adityastic** [comment]
@mariobehling @yashk2000 @iamareebjamal Review

**Comment by mariobehling** [comment]
Thank you. Please add a screenshot.

**Comment by adityastic** [comment]
@mariobehling Updated with screenshot

**Comment by mariobehling** [comment]
Changes are not very visible: Please decrease white space above top buttons, increase space above save/transfer, decrease space below save/transfer.

Make it in a way that an (invisible) circle would not overlap with the transfer button, please and leaves a bit space below it.

**Comment by adityastic** [comment]
I've removed the space above buttons competely, the 8dp margin is removed. Also added a 16dp padding above save/transfer and decresed the padding below the buttons from 32dp to 8dp. Here is the difference 
Before
Screenshot 2019-06-07 at 3 15 54 PM
After
Screenshot 2019-06-07 at 8 36 20 PM

**Comment by mariobehling** [comment]
Space between red underline and circle should be same as the space between the circle and the buttons below. Could you make it into the vertical centre, please?

**Comment by adityastic** [comment]
@mariobehling definitely

**Comment by adityastic** [comment]
@mariobehling here

Screenshot 2019-06-08 at 8 28 38 PM

**Comment by mariobehling** [comment]
Thank you

**Pull request merged**
