### PR TITLE
chore: Add Launcher Icon

### LINKED ISSUE #77: Make an icon for the app.
**Describe the chore**
There should be an icon for the app instead of the default android logo.

**Would you like to work on the issue?**
YES.

I was thinking of making the icon like the badgeyay website. Could you please give your opinions @iamareebjamal @mariobehling of how the app icon should be designed?

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #77 #176

Changes:
- Added Vectors and Drawables for the new Icon
- Updated Documentation with the Icon

Screenshots for the change:
iconpsd-5

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @yatri1609 @ShridharGoel @naman653 @anhanh11001 Please Peer Review

**Comment by adityastic** [comment]
@iamareebjamal have a look sir

**Comment by adityastic** [comment]
> Add an SVG of the vector icon as well

Hello Sir, Can you tell me the path inside the directory where you want the svg to be?

**Comment by iamareebjamal** [comment]
Root folder `ic_web.svg`

**Comment by adityastic** [comment]
@iamareebjamal Done :), have a look Sir

**Comment by adityastic** [comment]
@iamareebjamal any other changes required sir?

**Pull request merged**
