### PR TITLE
feat: implement drawing layout

### LINKED ISSUE #357: Implement a drawing mode
Implement a mode where the user can draw on the screen and create their own badge art.

1. Drawing mode should show the badge area in full in horizontal position.
2. The user can draw on the screen. There should be two functions
  a) draw (the user highlights anything s/he touches on the screen)
  b) delete (the user "unlights" anything s/he touches on the screen)

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #357 

Changes: 
- Added a layout that supports drawing

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal @CloudyPadmal @yashkhare2000 Review

**Comment by mariobehling** [comment]
Please check Travis is failing.

**Comment by mariobehling** [comment]
Please move "Tools" below badge display and
1. Take out the word "Tools".
2. Substitute "On/Off" with two buttons 
  a) Draw
  b) Erase

**Comment by yashk2000** [comment]
@adityastic great work :clap:

**Comment by adityastic** [comment]
@mariobehling dont merge yet. I just fixed the travis. need to make changes to the layout

**Comment by adityastic** [comment]
Updated Image, @mariobehling

**Comment by adityastic** [comment]
@mariobehling I am extremely sorry, I failed to understand your suggestions at the first time. I completely understand the requirements now. here is the updated screenshot. thank you

**Comment by iamareebjamal** [comment]
These icons look worse than pixelated PNGs, please use icons from here https://materialdesignicons.com/

**Comment by adityastic** [comment]
@iamareebjamal updated

**Comment by mariobehling** [comment]
Nice!

**Pull request merged**
