### PR TITLE
WIP: bottombar with viewpager for different sections

### LINKED ISSUE #151: Different Sections for Text and Drawable's inside the app.
**Describe the feature you'd like**
Currently, both the text and drawable are in the same screen. Different fragments will allow the user to have a better experience when selecting a text or a drawable.

**Additional context**
This will solve the issue of not being able to send the selected drawable to the LED Badge 

**Would you like to work on the issue?**
Yep, Im in

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #151 

Changes: 
- Added MainActivity with BottomBar and Viewpager implementation
- Added Two Fragments which will be worked upon by @yashk2000 and @yatri1609 (Text and Bitmap)

Screenshots for the change:

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic it looks good. I shall check it on my device. If it is working fine, i will start moving code to different fragments:)

**Comment by adityastic** [comment]
@yashk2000 great.

**Comment by iamareebjamal** [comment]
I don't think you need 2 separate fragments to show text and drawable when most of the screen is same. Just add a radio button or switch

**Comment by adityastic** [comment]
@iamareebjamal not 2, we need to have sections for text, bitmap and save and export. We plan to design the interface with the third fragment as save and export, which will allow users to preview the saved badge as well

**Comment by adityastic** [comment]
@iamareebjamal tell us your thoughts so we can reconsider the idea

**Comment by adityastic** [comment]
@iamareebjamal sir, we may increase the features as well later

**Comment by iamareebjamal** [comment]
That's fine. But I don't agree with bottom bar

**Comment by yatri1609** [comment]
@iamareebjamal ohk sir then I think we should reconsider the idea @adityastic @yashk2000

**Comment by adityastic** [comment]
@iamareebjamal any suggestions on how can we manage these sections?

**Comment by adityastic** [comment]
@yatri1609 yes ma'am, definitely. Should I close this pr?

**Comment by adityastic** [comment]
@iamareebjamal ok sir, can you give us some suggestions on managing these sections?

**Comment by yashk2000** [comment]
@iamareebjamal please give your ideas for managing the sections?

**Comment by yatri1609** [comment]
@adityastic let's close this and discuss on the channel itself that way we will get ideas from whole community.

**Comment by yashk2000** [comment]
@iamareebjamal could you please advise us on how we should implement the functionalities for managing the different sections?

**Pull request closed without merging**
