### PR TITLE
feat: Implement "Speed Wheel"

### LINKED ISSUE #233: Implement "Speed Wheel"
To control the speed of the text moving the user currently has to choose from a drop down menu "Mode". Instead please implement a visual interface for the speed.

Make it into a circle "wheel". The more to the right the user turns the faster it gets. 

Screenshot from 2019-04-25 00-22-03

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #233 

Changes: 
- Speed can now be controlled by a knob

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 Please Review

**Comment by adityastic** [comment]
@mariobehling Please Review Sir

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal Codacy flagged the pr with long and complex methods. Please have a look at it too

**Comment by mariobehling** [comment]
Thank you! Please check here the next step: https://github.com/fossasia/badge-magic-android/issues/248

**Comment by adityastic** [comment]
@mariobehling on it sir

**Pull request merged**
