### PR TITLE
chore: Release v1.1.0

### PR DESCRIPTION
**Pull request by adityastic**
Release v1.2.0

### CODE REVIEW

**Comment by adityastic** [comment]
@CloudyPadmal @mariobehling @iamareebjamal Please Review.

**Comment by iamareebjamal** [comment]
Why the next version from 1.0.1 is 1.2.0?

**Comment by adityastic** [comment]
@iamareebjamal 😂😂. Oh yeah, minor update xD

**Comment by iamareebjamal** [comment]
Change version name to 1.1.0

**Comment by adityastic** [comment]
@iamareebjamal on it

**Pull request merged**
