### PR TITLE
chore(docs): Added screenshots of the latest UI to the readme.

### LINKED ISSUE #193: Update screenshots of the app in README.md
**Describe the chore**
The screenshot of the app in the README.md is now outdated. NEw screenshots of the latest UI should be added in the README.md file.

**Would you like to work on the issue?**
YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #193 

Changes: Added screenshots of the latest UI to the README.md file.

Screenshots: 

Screenshot (1)
Screenshot (2)

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @adityastic please review.

**Comment by adityastic** [comment]
Can we have the screenshots of the hardware with the corresponding UI configuration?

**Comment by yashk2000** [comment]
Added the photos of the corresponding appearance on the hardware too.
[Here](https://github.com/yashk2000/badge-magic-android/tree/screenshots) is how the README looks now.

**Comment by adityastic** [comment]
@iamareebjamal looks good

**Comment by yashk2000** [comment]
@iamareebjamal please review.

**Comment by iamareebjamal** [comment]
Use github use content to upload images and use those instead of adding them in the repo

**Comment by yashk2000** [comment]
@iamareebjamal I made the changes. Please review.

**Comment by yashk2000** [comment]
@iamareebjamal currently I am not using tables to display the screenshots. Due to this, in mobile view, the images do not appear one below the other. Should I use tables to try and fix this?

**Comment by iamareebjamal** [comment]
Yes

**Comment by yashk2000** [comment]
@iamareebjamal done. Please review it.

**Pull request merged**
