### PR TITLE
fix: issues and improve Saved Badges screen

### LINKED ISSUE #306: Fix issues and improve Saved Badges screen when no badges are saved
Please change Saved Badges screen as follows, when no badges are saved:
* Ensure all design is showing on screen also for small screens
* Simplify smiley to one color using the design of a "Badge Smiley" instead of a full colored smiley

Screenshot_2019-05-16-20-02-43-147_org fossasia badgemagic

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #306 

Changes: 
- Improved Padding and Margin

Screenshots for the change:
Screenshot 2019-06-07 at 3 37 04 PM

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @mariobehling @iamareebjamal review

**Comment by mariobehling** [comment]
Thanks. Could you change the emoticon to look in the same way as our cliparts, please? So, we have a common design throughout the app.

**Comment by adityastic** [comment]
@mariobehling sure, let me create something similar

**Comment by adityastic** [comment]
@mariobehling updated, tell me your thoughts on this new icon

**Comment by cweitat** [comment]
My opinion is to just keep it simple with just a a sad face that can be typed out and sized up
image

**Comment by adityastic** [comment]
@cweitat yeah that looks better indeed

**Comment by mariobehling** [comment]
Something like the following as a sad smiley please:

Screenshot from 2019-06-08 15-54-49

**Comment by adityastic** [comment]
@mariobehling got it

**Comment by adityastic** [comment]
@mariobehling here is the new screeenshot
emoji

**Comment by mariobehling** [comment]
Thanks. The goal is to have a smiley in the design of the app - just like on badge itself. Let's spent some more time on this and get a smiley that is in the style of the cliparts.

**Comment by adityastic** [comment]
@mariobehling sure. Let me design something exactly like that emoji

**Comment by iamareebjamal** [comment]
Add pixelated emoji

**Comment by adityastic** [comment]
@iamareebjamal yes sir, I was out rn. Will add it as soon as I get back home

**Comment by adityastic** [comment]
Screenshot 2019-06-10 at 11 54 55 AM

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling let me know if you want me to design another emoji or this is fine

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
