### PR TITLE
feat : Implement a Drawer

### LINKED ISSUE #251: Implement a Drawer
Please implement a drawer similar to PSLab Android with the following:
* Create Badge
* Saved Badges
* About Us
* Feedback/Bug Reports (Link to Issue Tracker https://github.com/fossasia/badge-magic-android/issues)
* Buy Badge (https://sg.pslab.io)

view_navigation_drawer

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #251 

Changes:
- Added a Drawer Layout and Many other changes required for it to work

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 Thanks for your contribution, Please Review and send a PR for the about section after this PR

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal Please Review

**Comment by mariobehling** [comment]
Thank you! Please check if you could take care of this issue here: https://github.com/fossasia/badge-magic-android/issues/240

**Comment by adityastic** [comment]
@mariobehling Definitely sir, I will get #236 done first today. Will do #240 tomorrow for sure

**Pull request merged**
