### PR TITLE
(WIP) feat: added github pages

### LINKED ISSUE #410: prepare gh-pages
**Describe the feature you'd like**
gh pages for badge magic

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #410 

Changes: 
- Added Github Pages

Screenshots for the change:
bmtest

Test Link: 
https://sleepy-jackson-6ba79d.netlify.com

### CODE REVIEW

**Comment by cweitat** [comment]
Any URL to view it?

**Comment by adityastic** [comment]
@mariobehling yes I copied phimp.me's complete gh-pages and edited accordingly. Will update the screenshot and a test link soon

**Comment by adityastic** [comment]
@mariobehling @cweitat removed sidebar and update test link and screenshot.

**Comment by cweitat** [comment]
footer about link is different from the top navbar. footer donate as well.

**Comment by adityastic** [comment]
@cweitat fixing

**Pull request closed without merging**
