### PR TITLE
feat : Implement Animations(Marquee,Flash) in the Badge Preview

### LINKED ISSUE #93: Animations (Marquee, Flash) in Badge Preview of the App
**Description**
The Badge should react according to the selected animation. Currently it only displays the Text onto the preview.

**GIF of How it should work**
temp

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #93 
Changes: 
- Improved Accuracy of the badge by considering all the elements.
- Calculations are Changed for different cases.
- Improved the MessageActivity checkboxes, by avoiding both getting checked. Now only one checkbox will get checked no matter what.
- Added ValueAnimation to get the index according to the animation frame 

Screenshots for the change:
temp

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal Please review whenever you get time

**Comment by adityastic** [comment]
@iamareebjamal plz review the changes

**Comment by adityastic** [comment]
@iamabeerjamal Please review the PR

**Comment by adityastic** [comment]
@iamareebjamal Please Review the PR

**Comment by yashk2000** [comment]
@adityastic The flash effect looks good. But the marquee effect is not correct. The device has a different effect when the marquee is pressed.

**Comment by adityastic** [comment]
@yashk2000 Yes Yash. Different Modes are not implemented yet, this commit provides the base animation for both the options. Anyone can now add the conditions for different modes whenever this PR gets merged

**Comment by adityastic** [comment]
@iamareebjamal please review the pr

**Pull request closed without merging**
