### PR TITLE
remove unwanted strings

### LINKED ISSUE #623: Removing unwanted string quotes
**Describe the chore**
Removing unwanted string quotes for chinese text

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by tanmayrauth**
Fixes #623 

Changes: Remove unwanted string from chinese string file

### CODE REVIEW

**Comment by adityastic** [comment]
we don't need pr's which don't have motive tammany

**Comment by tanmayrauth** [comment]
Okay. But atleast can you fix it. Those quotes will be shown up when user uses app in chinese mode.

**Comment by adityastic** [comment]
@tanmayrauth you can merge it with any other fix

**Comment by adityastic** [comment]
@tanmayrauth you can merge it with productive pr :)

**Pull request closed without merging**
