### PR TITLE
fix: memory leak in fragments

### LINKED ISSUE #300: memory leak in maintextfragment
**Describe the bug**
there is a memory leak in maintextfragment due to anonynous listeners

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #300 

Changes: 
- declared all the listeners inside maintextfragment and stopped them accordingly
- removed rootview instance as it caused a major leak in every fragment

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal @yashk2000 @mariobehling review

**Comment by iamareebjamal** [comment]
And how does this fix the memory leak

**Comment by adityastic** [comment]
@iamareebjamal the textwatcher was getting added everytime when we rotated the screen

**Comment by adityastic** [comment]
@iamareebjamal the textwatcher was getting added everytime when we rotated the screen. As it was an anonymous declaration, it leaked. But now I fixed the scope to the fragment

**Comment by iamareebjamal** [comment]
It is still anonymous

**Comment by adityastic** [comment]
@iamareebjamal How can it be anonymous when I initialized it to a global variable

**Comment by adityastic** [comment]
@iamareebjamal how is it still anonymous when I initialized it to a global variable?. I need to remove the listener as well on 'onStop' dont merge this yet

**Comment by iamareebjamal** [comment]
> I need to remove the listener as well on 'onStop' dont merge this yet

This will stop the memory leak and not making it global. It is still anonymous even if you make it global. Anything implementing SAM without a concrete class is called anonymous inner class. You have just made it static

**Comment by iamareebjamal** [comment]
Sorry, it's not even static. There's literally no change in terms of memory leak and references from what it was before

**Comment by adityastic** [comment]
@iamareebjamal yes I forgot to include the call to the removelistener in onstop. I've added it locally yesterday, will push it once I reach home

**Comment by adityastic** [comment]
@iamareebjamal I get your point with anonymous class declaration. But if I don't initialize it globally I won't be able to remove the listener as removelistener accepts the object which needs to be removed

**Comment by adityastic** [comment]
@iamareebjamal, Damn you are right. The cause was something completely different, thanks for your suggestion man

**Comment by adityastic** [comment]
@iamareebjamal review

**Comment by iamareebjamal** [comment]
Why so many changes?

**Comment by adityastic** [comment]
@iamareebjamal the rootview was leaking

**Comment by iamareebjamal** [comment]
So?

**Comment by adityastic** [comment]
@iamareebjamal so I fixed it by not storing the view itself

**Comment by iamareebjamal** [comment]
Summarize your changes please

**Comment by adityastic** [comment]
- removed rootview instance
- removed listeners onStop and add listeners back onStart

**Comment by iamareebjamal** [comment]
Why do you need to change so many things for this?

**Comment by iamareebjamal** [comment]
Also, not storing a variable does not solve a memory leak. Just removing the listeners did the job

**Comment by adityastic** [comment]
@iamareebjamal there aren't so many changes. Every view was called like this rootView.textview. I just removed rootview from everything

**Comment by adityastic** [comment]
@iamareebjamal after removing the listeners, I got a leak regarding rootview and viewmodels.

**Comment by iamareebjamal** [comment]
Why did you change from lateinit var to nullable? There definitely are many changes unlrelated to memory leak which also reduce the code quality

**Comment by adityastic** [comment]
@iamareebjamal better now?

**Pull request merged**
