### PR TITLE
enhancement: Added about section

### LINKED ISSUE #259: Implement an about screen.
Implement an about screen as a first step use the info text from the Readme.md.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #259

Changes: Added an about section.

Screenshots for the change:
Screenshot_20190504-130220
Screenshot_20190504-123949

### CODE REVIEW

**Comment by yashk2000** [comment]
@mariobehling @iamareebjamal @adityastic please review.

**Comment by adityastic** [comment]
Center vertical align them according to the title and the subtitle of the layout on the right

**Comment by yashk2000** [comment]
@adityastic the size is the same as the GitHub icon. I will center align it. Just a minute.

**Comment by yashk2000** [comment]
@adityastic done. I reduced the icon size to 28dp for license icons.

**Comment by adityastic** [comment]
@yashk2000 please update the screenshot

**Comment by yashk2000** [comment]
@adityastic done.

**Pull request merged**
