### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by Rajchowdhury420**
Fixes #[Add issue number here. If you solve the issue entirely, else please change the message e.g. "First steps or Part of for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

**  If The app targets Android 9 or lower, declare
       ACCESS_COARSE_LOCATION instead **

### CODE REVIEW

**Comment by yashk2000** [comment]
@Rajchowdhury420 please create an issue before opening a pr and fill in the pr template while creating the pr. Also please follow semantic pr guidelines : https://github.com/probot/semantic-pull-requests/blob/master/README.md

**Comment by adityastic** [comment]
@Rajchowdhury420 also file an issue before submitting a pr. I've filled it for you as of now, please tag #498 in this Pull Request's description

**Comment by adityastic** [comment]
@Rajchowdhury420 plz finalize this

**Comment by Rajchowdhury420** [comment]
How ?

**Pull request closed without merging**
