### PR TITLE
Changed the way offsets were calculated for the background and the cells inside custom view

### LINKED ISSUE #90: Bug in Badge Preview for XXXHDPI Devices
**The Led's Layout is Uneven**

**To Reproduce**
Open the App in any XXXHDPI Device

**Screenshots**
bmex

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #90 

Changes: 
- Changed the way offsets were calculated
- Changed the way BgBounds were calculated

Screenshots for the change:
bmex2

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Properly name the PR

**Comment by adityastic** [comment]
@iamareebjamal On it, Sir.

**Comment by adityastic** [comment]
@iamareebjamal Done

**Comment by iamareebjamal** [comment]
Proper PR title would be `fix: Bound calculation in Preview custom view`

**Pull request merged**
