### PR TITLE
fix: Morphing Issues with Preview Badge

### LINKED ISSUE #370: Morphing Issues with Preview Badge
**Describe the bug**
morphing issues with preview badge

Screenshot 2019-06-13 at 9 19 20 AM

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #370 

Changes:
- Updates to Preview Badge

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @iamareebjamal @mariobehling Review

**Comment by mariobehling** [comment]
Unclear what problem you are solving.

**Comment by adityastic** [comment]
@mariobehling when you use this layout with other layouts, the behaviour is not what you expect. It will cut it's end from one side because the left and right offset are not fixed. Let me give you the screenshot asap

**Comment by adityastic** [comment]
@mariobehling Check the issue, I've added the image of the issue

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling plz get this merged

**Pull request merged**
