### PR TITLE
Support multiple frames

### LINKED ISSUE #638: Add 8 Storage Places as functionality to the app
The proprietary app of the LED Badges has a storage functionality for 8 types. Please add this functionality to the app.

These 8 Storage places mean the the badge LED art is stored directly on the badge itself.

Compare: https://play.google.com/store/apps/details?id=com.ls.shaheen.ledcard

Screenshot from 2020-01-30 18-16-51

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #638 

Changes:
- New "Transfer to badge" screen
- All transfer buttons now instead add to the "Transfer to badge" screen
- Transfer button on "Transfer to badge" screen sends all the (up to 8) frames to the badge

Screenshots for the change:
photo_2020-02-04_16-27-57
photo_2020-02-04_16-27-58
photo_2020-02-04_16-27-59
photo_2020-02-04_16-29-05

TODO (will need help with this, @adityastic):
- [ ] Fix text on badges in transfer queue
- [ ] Fix button alignment in transfer queue
- [ ] Automatically switch to Transfer to badge screen when hitting transfer on another screen

### CODE REVIEW

**Comment by adityastic** [comment]
@TheLastProject perfect 🤟. I'll busy with an assignment, will look at it tomorrow morning. Thanks a ton for the pr

**Comment by adityastic** [comment]
@TheLastProject great job 👍. I was just thinking of the process, should we send all the transfer to the transfer section or follow some better approach? Currently by this pr, if the person wants to transfer a single text they will be navigated to the transfer fragment and they need to manually get back to add more items to transfer. @iamareebjamal what are your thoughts on the workflow of this feature?

**Comment by TheLastProject** [comment]
If you look at the code and TODOs: "Automatically switch to Transfer to badge screen when hitting transfer on another screen" is planned for me. But I couldn't get that to work so I'll need help there.

**Comment by adityastic** [comment]
> If you look at the code and TODOs: "Automatically switch to Transfer to badge screen when hitting transfer on another screen" is planned for me. But I couldn't get that to work so I'll need help there.

Dont worry, I'll help you out with that. Lets get the workflow correct, then we can get this done

**Comment by adityastic** [comment]
@iamareebjamal please let me know your thoughts on this

**Comment by adityastic** [comment]
@iamareebjamal any updates? Should we move forward with this approach?

**Comment by iamareebjamal** [comment]
You know better about the project, so go ahead

**Comment by adityastic** [comment]
@iamareebjamal great. @TheLastProject If you're free, Please let me know. I'll drop a pr to your branch and let's get this working in the upcoming weekend 👍😊

**Comment by TheLastProject** [comment]
Sounds good, I'll have time to look at a PR this weekend probably

**Comment by TheLastProject** [comment]
Just gonna ping here again.

**Comment by FrankyBoy** [comment]
Hello, has anything happened here?

**Comment by adityastic** [comment]
> Hello, has anything happened here?

Not really. If you want to take it up, feel free to

**Comment by FrankyBoy** [comment]
<< has zero idea how anything mobile apps related works :D

**Comment by mariobehling** [comment]
@TheLastProject Hi, we are restarting work on this project. Would you like to fix the failing tests of this pull request?

**Comment by TheLastProject** [comment]
Well, in 3 years I guess my Android skills probably improved so I may be able to do the tasks without help now but I don't really have the time to finish this currently I'm afraid (still have a big to-do list on my own projects too) so it's probably best if someone else picks this up.

**Comment by mariobehling** [comment]
Closing this as we have moved to a flutter app now.

**Pull request closed without merging**
