### PR TITLE
feat: Implement "Effects" in same way as "Animations"

### LINKED ISSUE #245: Implement "Effects" in same way as "Animations"
Animations has been implemented with a boxes that show the animation immediately. Implement a section "Effects" below in the same way.

* Please take out the "colon" behind "Animations" as well. Don't add semicolons behind the section headings
* Also change "Send Drawables" to "Clipart" and "Send Text" to "Editor"

Screenshots for the change:
issue232

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #245

Changes: 
- Headings Changed
    - Send Drawables Changed -> Clipart
    - Send Text Changed to       -> Editor

- Added Visuals for Effects
- Effects now have a proper section
- accentColor is now primaryColor

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 Please Review

**Comment by mariobehling** [comment]
Nice! Please reduce the height of the effects tiles a bit.

**Comment by adityastic** [comment]
@mariobehling on it sir

**Comment by yashk2000** [comment]
> @yashk2000 Thanks for helping me in this pr, Please Review

@adityastic learned a lot again while collaborating with you :)

**Comment by adityastic** [comment]
@mariobehling I've updated the height to 64dp which is the standard height we are using for animations as well. I've Updated the Screenshots as well. Please Review

**Comment by adityastic** [comment]
@yashk2000 let's collaborate on some more issues, it was fun

**Comment by yashk2000** [comment]
@adityastic for sure :+1: It helps a lot in learning new stuff as well as getting things done faster.

**Comment by adityastic** [comment]
@mariobehling I've updated the height to 64dp which is the standard height we are using for animations as well. I've Updated the Screenshots as well. Please Review

**Comment by mariobehling** [comment]
Thank you!

**Comment by mariobehling** [comment]
Please follow up on the next issue here, if you like: https://github.com/fossasia/badge-magic-android/issues/233

**Comment by adityastic** [comment]
@mariobehling on it sir

**Pull request merged**
