### PR TITLE
Fixes #479 Edit Badge Screen / Edit Clipart Screen

### LINKED ISSUE #479: Edit Badge Screen / Edit Clipart Screen
1. Add an "Open Folder" icon to the edit badge screen on the top right of the screen on the menu bar. The icon should open "Saved Badges".
1. Add an "Open Folder" icon to the edit clipart screen on the top right of the screen on the menu bar. The icon should open "Saved Cliparts".

### PR DESCRIPTION
**Pull request by refactor-droidyy**
Fixes #479 Edit Badge Screen / Edit Clipart Screen
Add an "Open Folder" icon to the edit badge screen and edit clipart screen on the top right of the screen on the menu bar. The icon should open "Saved Badges" and "Saved Cliparts" respectively.

### CODE REVIEW

**Comment by refactor-droidyy** [comment]
@adityastic @mariobehling Please review

**Comment by adityastic** [comment]
Will do it today. Thanks

**Comment by refactor-droidyy** [comment]
@adityastic is this PR needs more changes?

**Comment by refactor-droidyy** [comment]
Saved Badge 

Screenshot_2019-11-18-11-11-05-047_org fossasia badgemagic

Saved Clipart

Screenshot_2019-11-18-11-11-22-685_org fossasia badgemagic

**Comment by refactor-droidyy** [comment]
@yashk2000 uploaded image for the issue solved Please review.

**Pull request closed without merging**
