### PR TITLE
chore : enabling bundler caching

### LINKED ISSUE #492: Improve Script by Caching Bundler
**Describe the bug**
Currently when the script runs, it takes 1-2 minutes just to download fastlane, we can cache the bundler to improve time

**Additional context**
Use Travis to Cache bundler

### PR DESCRIPTION
**Pull request by klutzayyyy**
Fixes #492 
Changes: 
- enabled bundler

### CODE REVIEW

**Comment by klutzayyyy** [comment]
@adityastic , @iamareebjamal please review

**Comment by adityastic** [comment]
Please follow symantic pr naming https://github.com/probot/semantic-pull-requests/blob/master/README.md

**Comment by klutzayyyy** [comment]
updated pr title @adityastic

**Comment by adityastic** [comment]
Please update the commit title as well

**Comment by adityastic** [comment]
@klutzayyyy please squash commits into a single commit https://github.com/fossasia/pslab-android#how-to-git-squash

**Pull request merged**
