### PR TITLE
feat: option to edit badges

### LINKED ISSUE #261: Implement an Edit button for saved badges
The badges on the saved badges screen are missing the option to edit them. Please implement it.

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #261 

Changes:
- redirect users to draw layout

Screenshots:
Before:

On Edit:

After Edit:

On Save:

On Save Preview:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @mariobehling @iamareebjamal review

**Comment by adityastic** [comment]
@mariobehling @yashk2000 @iamareebjamal review

**Comment by iamareebjamal** [comment]
PRF

**Comment by adityastic** [comment]
@iamareebjamal hey areeb, I'm not sure what am I missing from the format. Proper name ✓, Single Commit ✓, Mentioning Fixed Issue ✓, Screenshot for change ✓. Is there anything more?

**Comment by mariobehling** [comment]
Maybe better provide single screenshots in future. This Gif is too fast. Difficult to see.

**Comment by adityastic** [comment]
@mariobehling got it

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal  Updated with screenshots, have a look

**Comment by mariobehling** [comment]
Nice. Thank you! Let's try this in production.

**Pull request merged**
