### PR TITLE
enhancement: changed clipart switcher icon

### LINKED ISSUE #354: Enhance Emoticon/Text Icon Editor Choice
The icon for emoticons looks different to what people are used to in Whatsapp etc. Please use a smiley to show the emoticon options and use a keyboard symbol to switch to text editing. Please compare to Whatsapp.

Screenshot 2019-06-07 at 3 15 54 PM

nexus2cee_whatsapp-material-8

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #354 

Changes:
- improved emoji in text fragment

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @iamareebjamal @mariobehling Please Review

**Comment by adityastic** [comment]
@mariobehling, Updated

**Comment by mariobehling** [comment]
Why was this closed? We need a solution to this asap.

**Comment by adityastic** [comment]
@mariobehling check 368. It got closed accidentally, we merged the new pr btw

**Pull request closed without merging**
