### PR TITLE
Badge Preview Top Screen

### PR DESCRIPTION
**Pull request by anshulmak**
Part of for issues #14 

Fixed a part of the issue#14 by implementing a badge preview at the top of the screen and syncing the message to be send with the text of badge preview.

Screenshots for the change:

Screenrecorder201903121859

### CODE REVIEW

**Comment by yashk2000** [comment]
I don't think this is what is needed. We need a preview of how it looks in the actual badge. This is simply a representation of the text the user types in a black background.

**Comment by anshulmak** [comment]
> I don't think this is what is needed. We need a preview of how it looks in the actual badge. This is simply a representation of the text the user types in a black background.

**Comment by anshulmak** [comment]
> I don't think this is what is needed. We need a preview of how it looks in the actual badge. This is simply a representation of the text the user types in a black background.

I have used an led screen image as background just like an actual badge and after this i was thinking to apply the animations to the text according to the mode selected in the app. 

Can you please recommend me what can i do to implement a badge preview screen?

**Comment by sparrow007** [comment]
> I don't think this is what is needed. We need a preview of how it looks in the actual badge. This is simply a representation of the text the user types in a black background.

@yashk2000 would you show how it will looks for clarity ??

**Pull request closed without merging**
