### PR TITLE
fix: spinners and checkbox now trigger automatic preview

### LINKED ISSUE #184: Automatic Preview not getting triggered for Spinners and Checkboxes
**Describe the bug**
The Automatic Preview Does not work for spinners and checkboxes

**Expected behavior**
Automatic Preview should work on all widgets

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #184 

Changes:
- Added Listeners for Checkboxs
- Added Listeners for Spinners

Screenshots for change:
ezgif com-resize

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal Have a look sir

**Comment by ShridharGoel** [comment]
@adityastic Please add a GIF.

**Comment by adityastic** [comment]
> @adityastic Please add a GIF.

Sure, Just a min

**Comment by adityastic** [comment]
@iamareebjamal check this sir.

**Comment by iamareebjamal** [comment]
Peer Review first

**Comment by adityastic** [comment]
@iamareebjamal Peer Review done sir. @ShridharGoel thanks sir

**Pull request merged**
