### PR TITLE
Implementing Animation

### LINKED ISSUE #14: Implement a badge preview on the top of the screen
There are a number of apps to use the phone as an LED screen. Please take inspiration and implement a preview screen to show how it will look on the actual device on the top. Compare for example to this app: https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

### LINKED ISSUE #16: Implement animations
There are a number of nice animations possible with LED. Please check out this app and implement animations that work on real devices: https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

### PR DESCRIPTION
**Pull request by ark786**
Fixes #16 
Changes: 
1->Google Services dynamic font "raleway_dots" for LED fonts
2->xml files for marquee and flash animations
3->In message_activity.xml  ,
       Replaced checkboxes for marquee and flash with radio buttons( put in radio group) 
       Added button to stop and start preview
       Added TextView for Preview at top to display preview animations
4-> Made corresponding changes to load and stop animations in preview textView and changes to set 
      text for preview button
5->added color black to color resource file
6->added default words for Preview textView and Preview button

Screenshots for the change: 
final1

### CODE REVIEW

**Comment by yatri1609** [comment]
Please squash the commits and fix the merge conflicts. :)

**Comment by iamareebjamal** [comment]
Good work. Ask for peer review first. Also, use Google Services dynamic font provider instead of static ttf

**Comment by ShridharGoel** [comment]
Shouldn't the preview look as it looks on the real device?

**Comment by iamareebjamal** [comment]
That would be limitation of the font. Try to find a better font

**Comment by ark786** [comment]
Please review it and suggest changes :)

**Pull request closed without merging**
