### PR TITLE
feat: Change "Mode" to visual interpretation

### LINKED ISSUE #232: Change "Mode" to visual interpretation
To control the direction of the text moving the user currently has to choose from a drop down menu "Mode". Instead of the mode, please implement a visual interface that shows a small animation similar to https://play.google.com/store/apps/details?id=com.rooftopSpace.Led

Screenshot from 2019-05-01 15-16-53

See "Mode" below

Screenshot from 2019-04-25 00-22-03

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #232

Changes: 
- Mode is now Animation and It Displays animation from the led

Screenshots for the change:
issue232

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @iamareebjamal @mariobehling Please Review

**Comment by yashk2000** [comment]
The changes seem to be fine. Just fix the Travis issues.

**Comment by adityastic** [comment]
@yashk2000 glide itself had issues with androidx, fixed it :)

**Comment by adityastic** [comment]
@iamareebjamal @mariobehling Please Review

**Comment by mariobehling** [comment]
Good job. Let's see how that works out. Snowflake is not so clear for me yet, but can be improved later.

Please check if you could also do this with "Effects" https://github.com/fossasia/badge-magic-android/issues/245 Thanks!

**Comment by mariobehling** [comment]
I also need to check in more detail if the red color is the same as on the top area. If not, please change it in subsequent PRs.

**Comment by adityastic** [comment]
@mariobehling The red color is currently the accent color. I will change it to primary color as well as create the effects visually in the upcoming pr by today

**Comment by adityastic** [comment]
@mariobehling about the snowflake, it is visible only if the characters go beyond the badge, I will try to create another animation which depicts it perfectly sometime later this week

**Pull request merged**
