### PR TITLE
fix: Edittext hint and alert added

### LINKED ISSUE #65: Issue when edit text is empty.
**Describe the bug**
When the edit text is empty, the keyboard goes down and no alert is shown.

**To Reproduce**
Keep the edit text empty and press send. The keyboard goes down.

**Expected behavior**
The keyboard should not go down and an alert should be shown in the edit text.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 plus|
|Android Version|Android 9,0  |

**Additional context**
A hint shall also be added to the edit text. 

Update: Now the preview button has been introduced. Changes have to made for it also.

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #65 

Changes: A hint has been added to the exit text and an alert is shown if the user presses n when edit text is empty.

Screenshots for the change:

screencap

screencap1

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Use TextInputLayout

**Comment by yashk2000** [comment]
Ok. I will update the pull request with the changes.

**Comment by cweitat** [comment]
Conflict pls fix

**Comment by yashk2000** [comment]
This issue is no longer relevant.

**Pull request closed without merging**
