### PR TITLE
fix: Do not show emoticons always

### LINKED ISSUE #339: Do not show emoticons always. Follow methods similar to messengers like whatsapp
Currently the emoticons and text always cover the screen. Please change the features as follows:
* Portray a small emoticon or text button similar to Whatsapp on the left side of the editing field
* Show a button on the editor in blue (like before) to minimize the keyboard
* Don't allow multiple lines (as the actual device does not offer that feature!)

Screenshot_2019-05-27-21-29-41-025_com whatsapp

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #339 

Changes:
- Added a Clipart button

Screenshots for the change:

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal @yashk2000 @mariobehling Please Review

**Comment by yashk2000** [comment]
@adityastic is it possible to show to attach icon on the edit text itself? Like in WhatsApp, the message edittext itself has the icons for insert file or camera.

**Comment by adityastic** [comment]
Yes, Sure.

**Comment by adityastic** [comment]
@yashk2000 updated

**Comment by adityastic** [comment]
@mariobehling @iamareebjamal review

**Pull request merged**
