### PR TITLE
WIP: Added a horizontal spinner for selecting speed.

### LINKED ISSUE #233: Implement "Speed Wheel"
To control the speed of the text moving the user currently has to choose from a drop down menu "Mode". Instead please implement a visual interface for the speed.

Make it into a circle "wheel". The more to the right the user turns the faster it gets. 

Screenshot from 2019-04-25 00-22-03

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #233 

Changes: Added a spinner wheel to select the speed.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic please provide feedback. Some more work has to be done on this. If this satisfactory then I'll proceed.

**Comment by yashk2000** [comment]
Screenshot_20190501-164128 (2)

This is how the horizontal spinner looks like. Things to be done yet: 
- Replace `speed.selectedItemPosition` with data from the new spinner.
- Make preview update automatically when spinner data is changed.
- Some java code has been used currently. It will be converted to kotlin.

@adityastic please provide your feedback. If it is alright, I'll complete these things.

**Comment by adityastic** [comment]
Looks great to me. Can I make the rest of the changes ?

**Comment by yashk2000** [comment]
@adityastic sure. You can work on some of the remaining issues. We can then co-author this pr.

**Comment by adityastic** [comment]
@yashk2000 thanks man

**Comment by yashk2000** [comment]
@adityastic can you please send a pr? I destroyed my branch by mistake😅

**Pull request closed without merging**
