### PR TITLE
feat: Improve Edit Clipart Screen - Size and Buttons

### LINKED ISSUE #481: Improve Edit Clipart Screen - Size and Buttons
The Edit Clipart screen does not use the space optimally.

Please change and fix the following:
* Increase the size of the badge
* Decrease the size of the buttons, but ensure the spacing between buttons is sufficient to tab them on the phone
* Use the same rounded corners of the badge on all four badge corners.

Expected something like this:
63246419-ee2cae80-c262-11e9-97d5-f649392f1eb3

Currently looks like that:
Screenshot_20190819_092055_org fossasia badgemagic

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #481

Changes
- fixed dimens for buttons

Screenshots for the change:
gg

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic how will it loo if we shift the button to directly under the badge? Like right now they are a bit to the left of the badge.

**Comment by adityastic** [comment]
@yashk2000 yes we can. @mariobehling suggestions?

**Comment by mariobehling** [comment]
Please increase width and height of badge area as shown in the image below.

63246419-ee2cae80-c262-11e9-97d5-f649392f1eb3

**Comment by adityastic** [comment]
@mariobehling if we increase the height and width of the badge, it will lead to two cases:
1. The buttons won't have enough space to be visible
2. The badge will get streched

Currently the badge adjusts itself to fit it's height regardless of the width untill the width is less than the available width. Please update me accordingly

**Comment by mariobehling** [comment]
Please move the buttons to the bottom of the screen and use the free space to increase the badge. Don't stretch it, just increase the dimension in proportion to the max possible.

**Comment by mariobehling** [comment]
@adityastic Please finalize this PR.

**Comment by adityastic** [comment]
@iamareebjamal plz review

**Pull request merged**
